import 'package:flutter/material.dart';
import '../models/produkt_do_zamowienia.dart';
import '../services/zamowienie_service.dart';

enum Lokal { slawka, ruczaj }

class StanyPage extends StatefulWidget {
  const StanyPage({super.key});

  @override
  State<StanyPage> createState() => _StanyPageState();
}

class _StanyPageState extends State<StanyPage> {
  Lokal? wybranyLokal;
  final TextEditingController _pracownikController = TextEditingController();
  List<ProduktDoZamowienia> produkty = [];

  void _zaladujProduktyDlaLokalu(Lokal lokal) {
    final lokalNazwa = lokal == Lokal.slawka ? 'Sławka' : 'Ruczaj';
    final pracownik = _pracownikController.text.trim();

    if (pracownik.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Podaj imię pracownika')),
      );
      return;
    }

    final teraz = DateTime.now();
    final czas = '${teraz.hour.toString().padLeft(2, '0')}:${teraz.minute.toString().padLeft(2, '0')}';

    produkty = [];

    if (lokal == Lokal.slawka) {
      produkty.addAll([
        ProduktDoZamowienia(
          nazwa: 'Bazylia',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Borowiki',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Bresaola',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mozzarella di Bufala',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Burrata',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cebula czerwona',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cotto',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cukier',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cukinia',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Czosnek',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Fior di latte',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Gorgonzola',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Grana Padano',
          ilosc: 0,
          dostawca: 'KUCHNIE / MILLIE ',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Gruszka',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Rolada kozia',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Krewetki',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mąka REGINA',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Masło',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Inne',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Miód',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mleko',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mortadella',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Nduja',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mąka NUVOLA',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Oliwa',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Oliwki',
          ilosc: 0,
          dostawca: 'CHEFS / KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Oregano suszone',
          ilosc: 0,
          dostawca: 'FOOD',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Orzechy włoskie',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pancetta',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Papryka 1kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pasta truflowa',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pecorino Romano',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pelati',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Peperoncino',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pesto bazyliowe',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pieczarki 3kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pieprz mielony',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pietruszka',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pistacje',
          ilosc: 0,
          dostawca: 'FOOD',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pomidorki 2,5kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Prosciutto crudo',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Ricotta',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Rozmaryn',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Rukola',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Salami Napoli',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Semolina',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Śmietanka',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Sól',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Speck',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Spianata piccante',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Szpinak',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Tuńczyk po 3szt',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Tymianek',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Woda gazowana 1,5l',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Woda niegazowana 1,5l',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
      ]);
    }

    if (lokal == Lokal.ruczaj) {
      produkty.addAll([
        ProduktDoZamowienia(
          nazwa: 'Bakłażan',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Bazylia',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Borowiki',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Bresaola',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mozzarella di Bufala',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Burrata',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cebula biała 2kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cebula czerwona 5kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Chabry',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Chilli w płatkach',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cotto',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cukier',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cukinia',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Cytryny 2kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Tagliatelle czarne',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Czosnek',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Fettuccine',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Fior di latte',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Gałka muszkatołowa',
          ilosc: 0,
          dostawca: 'FOOD',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Gnocchi buraczkowe',
          ilosc: 0,
          dostawca: 'FOOD',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Gnocchi szpinakowe',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Gorgonzola',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Grana Padano',
          ilosc: 0,
          dostawca: 'KUCHNIE / MILLIE ',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Gruszka',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Guanciale',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Kalafior',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Rolada kozia',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Krewetki',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Lasagne',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Lody pistacjowe - kuweta',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mąka REGINA',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Masło',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Inne',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mięso mielone wieprzowe',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mięso mielone wołowe',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mięta',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Migdały płatki 0,5kg',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Miód',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mleko',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mortadella',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Nduja',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Mąka NUVOLA',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Oliwa',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Oliwki',
          ilosc: 0,
          dostawca: 'CHEFS / KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Oregano suszone',
          ilosc: 0,
          dostawca: 'FOOD',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Orzechy włoskie',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pancetta',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Papryka 1kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pasta truflowa',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pecorino Romano',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pelati',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Peperoncino',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pesto bazyliowe',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pieczarki 3kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pieprz mielony',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pieprz ziarnisty',
          ilosc: 0,
          dostawca: 'FOOD',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pietruszka świeża',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pietruszka korzeń',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pistacje',
          ilosc: 0,
          dostawca: 'FOOD',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pomidorki 2,5kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Pomidor 1kg',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Profiterole',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Prosciutto crudo',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Ravioli z kurkami',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Ricotta',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Rozmaryn',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Rukola',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Salami Napoli',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Scamorza affumicata',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Sery',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Semolina',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Śmietanka - pizza',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Śmietanka - makarony',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Sól',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Spaghetti',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Speck',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Spianata piccante',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Wędliny',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Szpinak',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Tagliatelle',
          ilosc: 0,
          dostawca: 'KUCHNIE',
          kategoria: 'Makarony',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Tiramisu',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Mrożonki',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Tuńczyk po 3szt',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Tymianek',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Warzywa',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Woda gazowana 1,5l',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Woda niegazowana 1,5l',
          ilosc: 0,
          dostawca: 'CHEFS',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
        ProduktDoZamowienia(
          nazwa: 'Żółtka w płynie',
          ilosc: 0,
          dostawca: 'MILLIE',
          kategoria: 'Suche',
          lokal: lokalNazwa,
          pracownik: pracownik,
          dataZlozenia: teraz,
          czasZlozenia: czas,
        ),
      ]);
    }


    setState(() {});
  }

  void _zapiszDoSupabase() async {
    final service = ZamowienieService();
    final doWyslania = produkty.where((p) => p.ilosc > 0);

    for (final produkt in doWyslania) {
      await service.dodajZamowienie(produkt);
    }

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Zamówienie zapisane w chmurze ✅')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Container(
        decoration: const BoxDecoration(
          image: DecorationImage(
            image: AssetImage('assets/zaczatek.jpg'),
            fit: BoxFit.cover,
            opacity: 0.6,
          ),
        ),
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              children: [
                const Text(
                  'Stany – Zamówienie',
                  style: TextStyle(
                    fontSize: 26,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFFD2D4C8),
                  ),
                ),
                const SizedBox(height: 16),
                TextField(
                  controller: _pracownikController,
                  decoration: InputDecoration(
                    labelText: 'Imię pracownika',
                    filled: true,
                    fillColor: Color.fromRGBO(255, 255, 255, 0.8),
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                ),
                const SizedBox(height: 16),
                DropdownButtonFormField<Lokal>(
                  decoration: InputDecoration(
                    labelText: 'Wybierz lokal',
                    filled: true,
                    fillColor: Color.fromRGBO(255, 255, 255, 0.8),
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  value: wybranyLokal,
                  items: Lokal.values.map((lokal) {
                    return DropdownMenuItem(
                      value: lokal,
                      child: Text(lokal == Lokal.slawka ? 'Sławka' : 'Ruczaj'),
                    );
                  }).toList(),
                  onChanged: (value) {
                    wybranyLokal = value;
                    _zaladujProduktyDlaLokalu(value!);
                  },
                ),
                const SizedBox(height: 16),
                if (produkty.isNotEmpty)
                  Expanded(
                    child: ListView.builder(
                      itemCount: produkty.length,
                      itemBuilder: (context, index) {
                        final produkt = produkty[index];
                        return Container(
                          margin: const EdgeInsets.symmetric(vertical: 6),
                          decoration: BoxDecoration(
                            color: const Color(0xCCFF725E54),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Padding(
                            padding: const EdgeInsets.all(12.0),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  produkt.nazwa,
                                  style: const TextStyle(
                                    fontSize: 18,
                                    fontWeight: FontWeight.bold,
                                    color: Color(0xFFD2D4C8),
                                  ),
                                ),
                                const SizedBox(height: 4),
                                Text(
                                  produkt.dostawca,
                                  style: const TextStyle(
                                    fontSize: 14,
                                    color: Color(0xFFD2D4C8),
                                  ),
                                ),
                                const SizedBox(height: 8),
                                Row(
                                  children: [
                                    Expanded(
                                      child: TextField(
                                        decoration: InputDecoration(
                                          hintText: 'Ilość',
                                          filled: true,
                                          fillColor: Color.fromRGBO(255, 255, 255, 0.8),
                                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                                        ),
                                        keyboardType: TextInputType.number,
                                        onChanged: (val) {
                                          setState(() {
                                            produkt.ilosc = int.tryParse(val) ?? 0;
                                          });
                                        },
                                      ),
                                    ),
                                    const SizedBox(width: 12),
                                    Expanded(
                                      child: TextField(
                                        decoration: InputDecoration(
                                          hintText: 'Komentarz (opcjonalny)',
                                          filled: true,
                                          fillColor: Color.fromRGBO(255, 255, 255, 0.8),
                                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                                        ),
                                        onChanged: (val) {
                                          setState(() {
                                            produkt.komentarz = val;
                                          });
                                        },
                                      ),
                                    ),
                                  ],
                                )
                              ],
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                const SizedBox(height: 16),
                ElevatedButton.icon(
                  icon: const Icon(Icons.save),
                  label: const Text('Zapisz zamówienie'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF093824),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                    textStyle: const TextStyle(fontWeight: FontWeight.bold),
                  ),

                  onPressed: _zapiszDoSupabase,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
